### ISSUE TITLE
Some errors in Google search results page

### ISSUE THREAD

**Issue by liliang13** [zanetu/direct_google#7]
As follows：
![2016-10-04_205246](https://cloud.githubusercontent.com/assets/1751239/19075691/9e88a764-8a78-11e6-8374-6c7244132b08.png)

So I removed about the 'expose cached links' codes. Can I fork and republish this code with GPL license?

Thank you for your reply.

**Comment by zanetu** [comment]
You are using a mobile device, aren't you? Mobile devices are not currently supported but it would be nice of you to leave your device model along with OS version, browser version, userscript-manager version, etc. so that I could consider supporting it in the future. 

You can fork Direct Google as long as your fork is licensed under GPL version 2 or any later version.

**Comment by liliang13** [comment]
No, I did not use a mobile device. It's desktop.
My OS : Windows 7 64-bit Simplified Chinese Ultimate Version
Browser version : Firefox 49.0.1, Desktop version.
userscript-manager version : Greasemonkey 3.9

I removed about the 'expose cached links' codes, so this script working properly right now.

Thank you for your reply.

**Comment by zanetu** [comment]
I cannot reproduce your issue in a similar environment: 
Windows 7 64-bit Professional (American English)
Firefox 49.0.1
Greasemonkey 3.9

Screenshot: 
![ie](https://cloud.githubusercontent.com/assets/3144970/19137394/6f2ca83e-8b41-11e6-8e9f-60e019a2957d.png)

As your screenshot looks quite different from a typical results page on a desktop, I wonder if you are using custom stylesheets such as https://userstyles.org/styles/1781 . If that is the case, I will not try to "fix" this issue since it is not caused by Direct Google per se.

**Comment by liliang13** [comment]
- When I log in to my google account, the search results page looks like this, there will be some page dislocation.
  ![2016-10-06_191858](https://cloud.githubusercontent.com/assets/1751239/19150510/ccb4d946-8bf9-11e6-956a-da675d4841b2.png)
- When I log out of my google account,   the page is like yours, everything is normal. 
  ![2016-10-06_192428](https://cloud.githubusercontent.com/assets/1751239/19150649/83fe1ebe-8bfa-11e6-99a8-333cbb34682c.png)
- When I log in, I change the language to English, error occurred.

![20161006193319](https://cloud.githubusercontent.com/assets/1751239/19150848/dd47e5d0-8bfb-11e6-8506-996f6ba5c6e7.png)

I did not change any settings in Google, the search page style suddenly changes in last week. So I temporarily remove the codes.

I don't know what Google happened.

**Comment by zanetu** [comment]
I cannot reproduce your screenshots, even after logging in/out and changing language settings. But I now know why you are getting card-based results. [1-3]
Since only a small portion of Google users are chosen to test card-based layout and I am not among them, there is nothing I can or should do at the moment. (By the way, hacks like [4] do not seem to work. ) 

[1] http://www.theverge.com/2016/6/8/11881786/google-search-material-design-layout-test
[2] https://www.engadget.com/2016/06/08/google-search-material-design-test/
[3] https://searchenginewatch.com/2016/09/06/google-experiments-with-new-desktop-serp-layout/
[4] https://www.reddit.com/r/google/comments/4m1t0w/google_appear_to_be_testing_a_material_design/d4h6ej6

**Comment by liliang13** [comment]
OK, I will close this issue, and thank you for your help.

**Comment by zanetu** [comment]
I just ran into this issue in incognito mode and figured changing [`.after($(this))`](https://github.com/zanetu/direct_google/blob/beta/direct_google.user.js#L118) to `.after($(this)).parent().css('white-space', 'nowrap')` might do the trick. Since I could not reproduce it again in incognito mode, however, there is no way for me to verify that this solution always works.

**Comment by liliang13** [comment]
Thank you. There is no error right now.
